name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *' # Codziennie o północy
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch TryHackMe Badge
        run: |
          curl -o assets/thm_propic.png https://tryhackme.com/badge/3215831
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add assets/thm_propic.png
          git commit -m 'Update TryHackMe badge'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
