name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *' # Codziennie o północy
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Twoje_Użytkownik_TryHackMe"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
